version: '3'
services:
  api-tests:
    build: .
    volumes:
      - /app/allure-results
    command: ["mvn", "test"]

  allure:
    image: "frankescobar/allure-docker-service"
    depends_on:
      - api-tests
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - /app/allure-results
      - /app/default-reports